GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjIsIm5hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5Acm9ja2V0bWFpbC5jb20iLCJpYXQiOjE2OTc2ODM3NDcsImV4cCI6MTY5NzY4Mzc2Mn0.SrnkrVLmgPeNfdsWejJtQUR72qid1ZilQXYwRyDmA8U

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "Jember",
    "email": "Jember@rocketmail.com",
    "role" : "user",
    "password" : "Jember",
    "confirmPassword": "Jember"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "admin",
    "password": "admin"
}

###
GET http://localhost:4000/token

###
DELETE  http://localhost:4000/logout

###
DELETE  http://localhost:4000/users/4

