GET http://localhost:4000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjIsIm5hbWUiOiJiYWtvcndpbCIsImVtYWlsIjoiYmFrb3J3aWxAcm9ja2V0bWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlhdCI6MTY5NzM0MzI1NCwiZXhwIjoxNjk3MzQzMjc0fQ.SgrAN5NEai9UqhiRUW150E-q7oBdmUSP5_H-DOlxOe0

###
POST http://localhost:4000/users
Content-Type: application/json

{
    "name": "bakorwil",
    "email": "bakorwil@rocketmail.com",
    "role" : "bakorwil",
    "password" : "bakorwil",
    "confirmPassword": "bakorwil"
}

###
POST http://localhost:4000/login
Content-Type: application/json

{
    "name": "bakorwil",
    "password": "bakorwil"
}

###
GET http://localhost:4000/token

###
DELETE  http://localhost:4000/logout